Algoritmo "REPIT"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/10/2021
Var
// Seção de Declarações das variáveis 
REP:CARACTERE

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
REPITA
LEIA(REP)
ATE REP = ("OI")

Fimalgoritmo